apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: dc-metro-map
  namespace: lui
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: appstudio
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: dc-metro-map
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: dc-metro-map-
      labels:
        build.appstudio.openshift.io/application: appstudio
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: dc-metro-map
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: lui
    spec:
      params:
      - name: git-url
        value: https://github.com/sbose78/dc-metro-map
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:lui-dc-metro-map-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:7e9728af099c5db53dda5f60e97d2b75f7e00d7d
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: dc-metro-map/$(tt.params.git-revision)
    status: {}
status: {}
